openapi: 3.0.1
info:
  title: Online Order API
  version: 1.0.0
  description: A basic API for working with the swagger tools.

paths:
  /orders:
    summary: Get all of the order data.
    description: This path is used to retrieve order data form the orders.json file.
    get:
      summary: Gets order data
      description: Retrieve the order information from the orders.json file.
      operationId: get_orders
      responses:
        '200':
          description: Successful retrieval of order data.
          content:
            application/json:
              examples:
                orders:
                  value: |-
                    {
                      "orders": [
                        {
                          "name": "Carey Maynard",
                          "id": "001",
                          "state": "pending"
                        },
                        {
                          "name": "Angelo Ayala",
                          "id": "002",
                          "state": "canceled"
                        },
                        {
                          "name": "Regina Yates",
                          "id": "003",
                          "state": "pending"
                        },
                        {
                          "name": "Elliott Mcclure",
                          "id": "004",
                          "state": "pending"
                        }
                      ]
                    }
        '500':
          description: Server error.
          content:
            application/json:
              examples:
                Server error:
                  value: |-
                    {
                      "error": "An unexpected error occurred."
                    }
        default:
          description: Default error sample response
      tags:
        - Orders

  /neworder:
    summary: Add new orders
    description: This path is used to add new orders to the orders.json file.
    post:
      summary: Add new order to the orders.json file.
      description: This adds a new order to the orders.json file.
      operationId: new_order
      requestBody:
        description: A new order object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            example:
              name: John Smith
              id: "005"
              state: pending
      responses:
        '201':
          description: Order created successfully.
          content:
            application/json:
              examples:
                Order created:
                  value: |-
                    {
                      "message": "Order added successfully.",
                      "order": {
                        "name": "John Smith",
                        "id": "005",
                        "state": "pending"
                      }
                    }
        '400':
          description: Bad request â€“ invalid order data.
          content:
            application/json:
              examples:
                Bad name:
                  value: |-
                    {
                      "error": "Missing required fields."
                    }
        default:
          description: Default error sample response
      tags:
        - New_order

  /update/{id}:
    summary: Update the state of an order.
    description: This path is used to update the state of an order with a matching id in the orders.json file.
    parameters:
      - name: id
        in: path
        required: true
        description: The ID of the order to update.
        schema:
          type: string
    put:
      summary: Update an order
      description: This path updates the state of an order with a matching id in the orders.json file.
      operationId: update_order
      requestBody:
        description: Updated order data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            example:
              id: "002"
              name: "Angelo Ayala"
              state: pending
      responses:
        '200':
          description: Order updated successfully.
          content:
            application/json:
              examples:
                Order update:
                  value: |-
                    {
                      "message": "Order updated.",
                      "order": {
                        "id": "002",
                        "name": "Angelo Ayala",
                        "state": "pending"
                      }
                    }
        '404':
          description: Order not found.
          content:
            application/json:
              examples:
                Order not found:
                  value: |-
                    {
                      "error": "Order with the specified ID was not found."
                    }
        default:
          description: Default error sample response
      tags:
        - Update_order

  /delete/{id}:
    summary: Delete an order
    description: This path is used to delete an order with a matching id from the orders.json file.
    parameters:
      - name: id
        in: path
        required: true
        description: The ID of the order to delete.
        schema:
          type: string
    delete:
      summary: Deletes an order
      description: This path delet
